---
- name: setup tomcat
  hosts: all
  become: yes
  tasks:
  - name: Install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: download tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.73/bin/apache-tomcat-8.5.73.tar.gz
      des: /opt

  - name: extract tomcat
    unarchive:
      src: /opt/apache-tomcat-8.5.73.tar.gz
      dest: /opt
      remote_src: yes

  - name: Providing execute permissions
    file:
      path: /opt/apache-tomcat-8.5.73/bin/startup.sh
      mode: 0777

  - name: Start the tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.73/bin
