---
- hosts: all
  user: ansible
  become: yes
# root priviledge access
  become_method: sudo

  tasks:
  - name: Add influxdb repository
    yum_repository:
      name: influxdb
      description: InfluxDB Repository - RHEL $releasever
      baseurl: https://repos.influxdata.com/rhel/8/amd64/stable/influxdb-1.8.10.x86_64.rpm
      gpgcheck: yes
      gpgkey: https://repos.influxdata.com/influxdb.key

  - name: Install influxdb
    yum:
      name: influxdb
      state: latest

  - name: Copy config
    copy:
      src: ./influxdb.conf
      dest: /etc/influxdb/influxdb.conf
      backup: yes
      force: no
      notify:
      - restart influxdb

  handlers:
  - name: restart influxdb
    service:
      name: influxdb
      state: restarted
